"use client"; // Ensure this is treated as a client component

import Header from "../components/Header"; // Import the reusable Header component

export default function Features() {
  return (
    <div className="min-h-screen flex flex-col justify-between bg-gray-50 text-gray-800">
      <Header /> {/* Include the reusable header */}
      
      {/* Spacing to prevent content from being hidden under fixed header */}
      <div className="mt-20"></div>

      {/* Main Content */}
      <main className="flex-grow">
        <div className="max-w-7xl mx-auto py-16 px-4 sm:px-6 lg:px-8">
          <h1 className="text-4xl font-extrabold text-gray-900 mb-6">Features</h1>
          <p className="text-lg text-gray-600 mb-12">
            Explore the cutting-edge features TrustPass offers to keep your passwords secure and privacy intact.
          </p>

          {/* Grid for feature cards */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {/* Card 1: Password Strength Checker */}
            <div className="bg-gradient-to-r from-blue-500 to-indigo-500 text-white shadow-lg rounded-lg p-6 transition-transform transform hover:scale-105">
              <h2 className="text-2xl font-semibold mb-2">Password Strength Checker</h2>
              <p className="text-sm text-white/90">
                Evaluate the strength of your passwords with real-time feedback to ensure they meet modern security standards.
              </p>
            </div>

            {/* Card 2: No Data Stored */}
            <div className="bg-gradient-to-r from-green-500 to-teal-500 text-white shadow-lg rounded-lg p-6 transition-transform transform hover:scale-105">
              <h2 className="text-2xl font-semibold mb-2">No Data Stored</h2>
              <p className="text-sm text-white/90">
                All password processing happens locally on your device. No data is sent to the backend or stored on our servers.
              </p>
            </div>

            {/* Card 3: Secure Password Suggestions */}
            <div className="bg-gradient-to-r from-purple-500 to-pink-500 text-white shadow-lg rounded-lg p-6 transition-transform transform hover:scale-105">
              <h2 className="text-2xl font-semibold mb-2">Secure Password Suggestions</h2>
              <p className="text-sm text-white/90">
                Generate strong, secure passwords tailored to your needs with just a few clicks. No more weak or forgotten passwords!
              </p>
            </div>

            {/* Card 4: Real-Time Traffic Monitoring */}
            <div className="bg-gradient-to-r from-yellow-500 to-orange-500 text-white shadow-lg rounded-lg p-6 transition-transform transform hover:scale-105">
              <h2 className="text-2xl font-semibold mb-2">Real-Time Traffic Monitoring</h2>
              <p className="text-sm text-white/90">
                Monitor the network traffic generated by your actions, ensuring no sensitive data is transmitted to the backend.
              </p>
            </div>

            {/* Card 5: Privacy First Approach */}
            <div className="bg-gradient-to-r from-red-500 to-rose-500 text-white shadow-lg rounded-lg p-6 transition-transform transform hover:scale-105">
              <h2 className="text-2xl font-semibold mb-2">Privacy First</h2>
              <p className="text-sm text-white/90">
                TrustPass is built with privacy in mind. We prioritize protecting your personal information at all costs.
              </p>
            </div>

            {/* Card 6: Dark Web Monitoring (Optional Feature) */}
            <div className="bg-gradient-to-r from-gray-500 to-black text-white shadow-lg rounded-lg p-6 transition-transform transform hover:scale-105">
              <h2 className="text-2xl font-semibold mb-2">Dark Web Monitoring</h2>
              <p className="text-sm text-white/90">
                Stay ahead of security breaches by monitoring whether your passwords or emails appear in known data leaks.
              </p>
            </div>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-gray-800 text-white py-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <p className="text-lg">&copy; {new Date().getFullYear()} TrustPass. All rights reserved.</p>
          <p className="mt-2 text-sm text-gray-400">Privacy-first password safety, built with trust and security in mind.</p>
        </div>
      </footer>
    </div>
  );
}
