"use client"; // Add this directive at the very top

import { useState } from "react";
import Header from "../app/components/Header"; // Import the reusable Header component
import { Test } from "../../src/helperFunctions/test";

export default function Home() {
  const [password, setPassword] = useState(''); // Store the password input
  const [showPassword, setShowPassword] = useState(false); // Toggle password visibility

  const handlePasswordChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    console.log(Test());
    console.log(e.target.value)
    setPassword(e.target.value);
  };

  return (
    <div className="min-h-screen flex flex-col justify-between bg-gray-50 text-gray-800">
      <Header /> {/* Include the reusable header */}

      {/* Spacing to prevent content from being hidden under fixed header */}
      <div className="mt-20"></div>

      {/* Main Content */}
      <main className="flex-grow">
        <div className="max-w-7xl mx-auto py-16 px-4 sm:px-6 lg:px-8 grid grid-cols-1 md:grid-cols-2 gap-8">
          {/* Left Column: Password Checker */}
          <section className="bg-white shadow-xl rounded-lg p-8">
            <h2 className="text-3xl font-semibold mb-6 text-gray-900">Check Your Password's Strength</h2>
            <p className="mb-8 text-gray-600">
              Enter your password below to check its strength and security. All processing is done locally in your browser. We never store or send your password data anywhere.
            </p>

            <div className="relative mb-6">
            <input
              type={showPassword ? "text" : "password"} // Toggle between "text" and "password"
              value={password}
              onChange={handlePasswordChange} // This should trigger on every input change
              placeholder="Enter your password"
              className="w-full p-4 text-lg border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
            
              {/* Show/Hide Password Button */}
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute inset-y-0 right-0 px-4 py-3 text-gray-600 hover:text-gray-900"
              >
                {showPassword ? (
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-6 w-6"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M15 12h.01M12 12h.01M9 12h.01M9 9.25a4.5 4.5 0 016.146 6.226m-.39.944A4.5 4.5 0 019 9.25m6 0A4.5 4.5 0 009.5 15m6 6.5A4.5 4.5 0 0118.002 9"
                    />
                  </svg>
                ) : (
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-6 w-6"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M2 12c1.72-4.67 5.98-8 10-8s8.28 3.33 10 8-5.98 8-10 8-8.28-3.33-10-8zm10-3a3 3 0 100 6 3 3 0 000-6z"
                    />
                  </svg>
                )}
              </button>
            </div>

            <button 
              className="w-full py-3 px-6 bg-blue-600 text-white font-semibold rounded-lg text-lg hover:bg-blue-700 transition-all">
              Check Password
            </button>

            {/* Placeholder for password strength output */}
            <div className="mt-6 text-center">
              <p className="text-lg text-gray-700">
                Password Strength: <span className="font-semibold text-green-500">Strong</span>
              </p>
            </div>
          </section>

          {/* Right Column: Traffic Logs */}
          <section className="bg-gray-100 shadow-xl rounded-lg p-8">
            <h2 className="text-3xl font-semibold mb-6 text-gray-900">Traffic Monitor</h2>
            <p className="mb-8 text-gray-600">
              Below is the real-time network traffic generated by your activity on this page. No sensitive data is transmitted to the backend.
            </p>

            <div className="bg-white border border-gray-300 p-4 rounded-lg h-96 overflow-auto">
              <p className="text-gray-500 text-sm">No traffic generated yet...</p>
            </div>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-gray-800 text-white py-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <p className="text-lg">&copy; {new Date().getFullYear()} TrustPass. All rights reserved.</p>
          <p className="mt-2 text-sm text-gray-400">Privacy-first password safety, built with trust and security in mind.</p>
        </div>
      </footer>
    </div>
  );
}